### ISSUE TITLE
Marker - Massive Collecting

### ISSUE THREAD

**Issue by MohsenRezaeii** [robotopia-x/robotopia#132]
Hi.
I know my question is too basic, but I can't pass the Marker - Massive Collecting tutorial stage. This is the code block that I create:
![capture](https://cloud.githubusercontent.com/assets/27505140/25048476/e8dd0ac4-2151-11e7-9e60-af1b7335e995.JPG)
It works fine until the main robot finds a resource and places a marker. Right then all of the robots freeze and the Reset button stops working too. What am I doing wrong? I'm trying to understand the game so that I can teach it to some kids... Help please!

**Comment by paulsonnentag** [comment]
There was a bug in our code, my bad. I've fixed it so the online version should work now. Thanks for reporting it. You need to slightly change your blockly code for it to work though. The instructions should be clearer, we need to improve that.

The resource is only known inside of the 'when resource is discovered' block. Markers are completely independent of resources. There are just a general way for robots to communicate with each other. The markers are always placed at the current position of the robot and since the robot has a discovery range of 2 blocks the discovery event is triggered when the robot is a few blocks away from the resource. So the robot needs to move to the resource first and then place the marker.
 
Right now the only thing robots can do is collect resources but in the future we want to extend the gameplay so robots might be able to conquer the enemy base. In this case markers could be placed at the enemy base to gather enough robots to conquer it. That's also the reason why there are multiple marker colors so players could use different colors for different situations:

Here is a working version:

<img width="508" alt="screen shot 2017-04-14 at 22 01 00" src="https://cloud.githubusercontent.com/assets/650540/25054576/35a63e3c-215e-11e7-905d-315177912360.png">

I'm happy to hear that you want to use robotopia for teaching kids about programming. If you have any more questions or need support with something let me know. I'd be also interested to get your feedback how it went and what the stumbling blocks were.

**Comment by MohsenRezaeii** [comment]
You are starting something huge in the way of programming! Thank you, good luck, and keep up the good work.
I don't mean to sound too rude, but here are a few things that I didn't like about Robotopia:
1. After playing a few games, the page becomes too heavy and the controls (adding/moving blocks) don't work as swiftly and softly as the beginning.
2. I tried to install the local version. I downloaded and installed Git, and I ran the commands that you've included in your instructions. But I get the "npm is not recognized as an internal or external command, operable program or batch file" error. I'm not a pro at using Git and I'm not sure if I've done it correctly. But as a beginner, I think the installation instructions are not clear enough.

I only pointed out these things because I love Robotopia, and I think it's really an amazing project. That's why I want it to improve.
